import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Map To App",
	description: "Website that you enter the coordiantes and it asks which app to open (maps or waze). This whole code was generated by v0.dev",
	generator: "v0.dev"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
